### ISSUE TITLE
Build Evironment Error:return non zero exit status 9

### ISSUE THREAD

**Issue by ghost** [ni/nilrt#191] opened 2022-10-12 01:45 UTC
I run the env file as root, and got the error like:
`INFO: Using /home/lab/Downloads/nilrt/nilrt/build as the OE build workspace.
BB_NUMBER_THREADS=40
INFO: Using pyrex image: build-nilrt:hardknott
useradd: user 'root' already exists
Traceback (most recent call last):
  File "/usr/libexec/pyrex/entry.py", line 201, in <module>
    sys.exit(main())
  File "/usr/libexec/pyrex/entry.py", line 105, in main
    subprocess.check_call(
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['useradd', '--non-unique', '--uid', '0', '--gid', '0', '--groups', '0', '--home', '/root', '--no-create-home', '--shell', '/bin/sh', 'root']' returned non-zero exit status 9.
`

**Comment by amstewart** [comment] 2022-10-12 16:08
Did you use the [`create-build-nilrt.sh` script](https://github.com/ni/nilrt/blob/nilrt/master/hardknott/docker/create-build-nilrt.sh) to generate the docker container that pyrex uses?

If so, did you do anything different from what is [requested in the README](https://github.com/ni/nilrt/blob/nilrt/master/hardknott/README.md#set-up-pyrex)?

**Comment by amstewart** [comment] 2022-10-27 14:51
I'm going to close this issue, since there hasn't been any activity in a couple weeks. Let me know if you object.

**Comment by SallyTYT** [comment] 2023-03-21 04:06
> Did you use the [`create-build-nilrt.sh` script](https://github.com/ni/nilrt/blob/nilrt/master/hardknott/docker/create-build-nilrt.sh) to generate the docker container that pyrex uses?
> 
> If so, did you do anything different from what is [requested in the README](https://github.com/ni/nilrt/blob/nilrt/master/hardknott/README.md#set-up-pyrex)?

Hi @amstewart , I got this error too. I did use [create-build-nilrt.sh script](https://github.com/ni/nilrt/blob/nilrt/master/hardknott/docker/create-build-nilrt.sh) but still get this error. Do you have any other ideas about this issue? Thank you

**Comment by mike-petersen-ni** [comment] 2023-03-23 17:58
@GccNoSharp or @SallyTYT:

Could you provide more information on the environment in which you are encountering this issue?  
Let us know:
 - what distro you're using,
 - which nilrt branch you're using,
 - what steps you took to set up the system,
 - and other useful information.

<details><summary>A working example</summary>

In a VM running Ubuntu Desktop, version [22.04.02 LTS (Jammy Jellyfish)](https://releases.ubuntu.com/22.04.2/), running on a machine within the NI corporate network.

From a clean install, these commands (mostly from the README) are sufficient to set up the system, enter the bitbake environment, and use it to build:

1. Install git:
   ```bash
   sudo apt-get install git
   ```
2. Clone the repositories:
   ```bash
   git clone https://github.com/ni/nilrt.git
   cd nilrt
   git submodule init
   git submodule update --remote --checkout
   ```
3. Install the Docker engine [as described by their documentation](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository):
   - Install Docker packages:
      ```bash
      sudo apt-get update
      sudo apt-get install ca-certificates curl gnupg lsb-release
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      sudo apt-get update
      sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      ```
   - Add user to docker group:
      ```bash
      sudo usermod -a -G docker $USER
      ```
5. Reboot:
   ```bash
   reboot
   ```
6. Return to the nilrt clone:
   ```bash
   cd nilrt
   ```
7. Build the Docker container:
   ```bash
   ./docker/create-build-nilrt.sh
   ```
8. Set up the bitbake environment:
   ```bash
   . ./ni-oe-init-build-env
   echo 'NILRT_MAIN_FEED_VERSION = "2023Q1"' >> ./conf/local.conf
   ```
9. Use bitbake:
   ```bash
   bitbake python3
   ```

</details>

**Comment by SallyTYT** [comment] 2023-03-28 02:22
@mike-petersen-ni thank you for your reply. For your listed questions,

- what distro you're using, ---- CentOS Linux release 7.9.2009 (Core)
- which nilrt branch you're using, ---- nilrt/master/hardknott
- what steps you took to set up the system, ---- strictly follow the [README.md](https://github.com/ni/nilrt#entering-the-bitbake-build-environment)
- and other useful information.

I will try with Ubuntu, thank you.

**Comment by mike-petersen-ni** [comment] 2023-03-28 15:37
@SallyTYT
I've tried a VM running a [Minimal installation of CentOS 7.9.2009 (Core)](http://isoredirect.centos.org/centos/7/isos/x86_64/) and was able to successfully enter the environment and run a bitbake build. At a high level, the steps I took were:

 - `sudo yum install git python3`
 -  followed the README instructions
    - for Docker, using [their installation instructions](https://docs.docker.com/engine/install/centos/#install-using-the-repository) and [adding the user to the `docker` group](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user)

Let us know if you have suggestions to improve clarity in our instructions, or if you continue to encounter the issue.

**Comment by SallyTYT** [comment] 2023-03-30 03:42
@mike-petersen-ni It turns out that I was using the root user to execute all the commands, which led to the issue. I switched to a normal privileged user and added the user to the docker group, then it worked. Thank you very much!

**Comment by mike-petersen-ni** [comment] 2023-03-30 17:33
I've been able to reproduce this issue by sourcing the `ni-oe-init-build-env` script as `root`. We'll look into improving the error reporting ([AB#2350311](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2350311)). For now, it sounds like normal usage isn't causing problems; closing this item as resolved.

**Closed as completed by mike-petersen-ni** 2023-03-30 17:33 UTC
